### ISSUE TITLE
Unable to make payment using BitPay

### ISSUE THREAD

**Issue by feelinc** [bitpay/magento2-plugin#30]
### Preconditions
1. PHP 7.x
2. Magento 2.1.9

### Steps to reproduce
1. Add a product to shopping cart
2. Go to checkout
3. Pay using Bitcoin

### Expected result
1. BitPay modal should appear.

### Actual result
1. Error.

![selection_359](https://user-images.githubusercontent.com/345562/32211356-ba9fa32a-be44-11e7-98f6-f8120820bc1f.jpg)

main.CRITICAL: Exception: Notice: Object of class DateTime could not be converted to int in /path/to/mag/web/app/code/Bitpay/Core/Model/Method/Bitcoin.php on line 229 in /path/to/mag/web/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /path/to/mag/web/app/code/Bitpay/Core/Model/Method/Bitcoin.php(229): Magento\Framework\App\ErrorHandler->handler(8, 'Object of class...', '/path/to/mag/web/app/co...', 229, Array)
#1 /path/to/mag/web/vendor/magento/module-sales/Model/Order/Payment/Operations/AuthorizeOperation.php(45): Bitpay\Core\Model\Method\Bitcoin->authorize(Object(Bitpay\Core\Model\Order\Payment\Interceptor), 14.4)
#2 /path/to/mag/web/vendor/magento/module-sales/Model/Order/Payment/Processor.php(72): Magento\Sales\Model\Order\Payment\Operations\AuthorizeOperation->authorize(Object(Bitpay\Core\Model\Order\Payment\Interceptor), true, 14.4)
#3 /path/to/mag/web/vendor/magento/module-sales/Model/Order/Payment.php(1054): Magento\Sales\Model\Order\Payment\Processor->authorize(Object(Bitpay\Core\Model\Order\Payment\Interceptor), true, 14.4)
#4 /path/to/mag/web/vendor/magento/module-sales/Model/Order/Payment.php(421): Magento\Sales\Model\Order\Payment->authorize(true, 14.4)
#5 /path/to/mag/web/app/code/Bitpay/Core/Model/Order/Payment.php(68): Magento\Sales\Model\Order\Payment->processAction('authorize', Object(Magento\Sales\Model\Order))
#6 /path/to/mag/web/vendor/magento/module-sales/Model/Order.php(858): Bitpay\Core\Model\Order\Payment->place()
#7 /path/to/mag/web/vendor/magento/module-sales/Model/Order.php(1047): Magento\Sales\Model\Order->_placePayment()
#8 /path/to/mag/web/vendor/magento/module-sales/Model/Service/OrderService.php(190): Magento\Sales\Model\Order->place()
#9 /path/to/mag/web/vendor/magento/module-quote/Model/QuoteManagement.php(488): Magento\Sales\Model\Service\OrderService->place(Object(Magento\Sales\Model\Order))
#10 /path/to/mag/web/vendor/magento/module-quote/Model/QuoteManagement.php(391): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote), Array)
#11 /path/to/mag/web/vendor/magento/module-quote/Model/QuoteManagement.php(349): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote))
#12 /path/to/mag/web/vendor/magento/module-checkout/Model/PaymentInformationManagement.php(79): Magento\Quote\Model\QuoteManagement->placeOrder(339)
#13 /path/to/mag/web/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(339, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
#14 /path/to/mag/web/var/generation/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(26): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)
#15 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder(339, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))
#16 /path/to/mag/web/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)
#17 /path/to/mag/web/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
#18 /path/to/mag/web/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /path/to/mag/web/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
#20 /path/to/mag/web/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Webapi\\...', 'dispatch', Object(Magento\Webapi\Controller\Rest\Interceptor), Array, 'infortis_cgen_m...')
#21 /path/to/mag/web/app/code/Infortis/Cgen/Plugin/Magento/Framework/App/FrontController.php(32): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#22 /path/to/mag/web/vendor/magento/framework/Interception/Interceptor.php(142): Infortis\Cgen\Plugin\Magento\Framework\App\FrontController->aroundDispatch(Object(Magento\Webapi\Controller\Rest\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#23 /path/to/mag/web/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#24 /path/to/mag/web/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /path/to/mag/web/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#26 /path/to/mag/web/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#27 {main} [] []

**Comment by feelinc** [comment]
Fixed #31
