### ISSUE TITLE
After running the pairing the site crashes magento 2.2

### ISSUE THREAD

**Issue by ray-moncada** [bitpay/magento2-plugin#37]
I installed the Bitpay_Core-1.0.5.zip file.

I am able to work on the back end, when I enter the information in the bitpay admin panel to pair the site. the site crashes and I get the following error.

InvalidArgumentException: Invalid scope type 'en_US' in /html/lib/internal/Magento/Framework/App/ScopeResolverPool.php:40 Stack trace: 
#0 /html/lib/internal/Magento/Framework/App/Config/ScopeCodeResolver.php(48): Magento\Framework\App\ScopeResolverPool->get('en_US') 
#1 /html/app/code/Magento/Config/App/Config/Source/RuntimeConfigSource.php(87): Magento\Framework\App\Config\ScopeCodeResolver->resolve('en_US', '0') 
#2 /html/app/code/Magento/Config/App/Config/Source/RuntimeConfigSource.php(63): Magento\Config\App\Config\Source\RuntimeConfigSource->loadConfig() 
#3 /html/lib/internal/Magento/Framework/App/Config/ConfigSourceAggregated.php(40): Magento\Config\App\Config\Source\RuntimeConfigSource->get('') 
#4 /html/app/code/Magento/Config/App/Config/Type/System/Reader.php(60): Magento\Framework\App\Config\ConfigSourceAggregated->get() 
#5 /html/generated/code/Magento/Config/App/Config/Type/System/Reader/Proxy.php(95): Magento\Config\App\Config\Type\System\Reader->read() 
#6 /html/app/code/Magento/Config/App/Config/Type/System.php(292): Magento\Config\App\Config\Type\System\Reader\Proxy->read() 
#7 /html/app/code/Magento/Config/App/Config/Type/System.php(191): Magento\Config\App\Config\Type\System->readData() 
#8 /html/app/code/Magento/Config/App/Config/Type/System.php(152): Magento\Config\App\Config\Type\System->loadDefaultScopeData('default') 
#9 /html/lib/internal/Magento/Framework/App/Config.php(131): Magento\Config\App\Config\Type\System->get('default/newreli...') 
#10 /html/lib/internal/Magento/Framework/App/Config.php(80): Magento\Framework\App\Config->get('system', 'default/newreli...') 
#11 /html/app/code/Magento/NewRelicReporting/Model/Config.php(91): Magento\Framework\App\Config->getValue('newrelicreporti...') 
#12 /html/app/code/Magento/NewRelicReporting/Plugin/HttpPlugin.php(49): Magento\NewRelicReporting\Model\Config->isNewRelicEnabled() 
#13 /html/lib/internal/Magento/Framework/Interception/Interceptor.php(121): Magento\NewRelicReporting\Plugin\HttpPlugin->beforeCatchException(Object(Magento\Framework\App\Http\Interceptor), Object(Magento\Framework\App\Bootstrap), Object(InvalidArgumentException)) 
#14 /html/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Bootstrap), Object(InvalidArgumentException)) 
#15 /html/generated/code/Magento/Framework/App/Http/Interceptor.php(39): Magento\Framework\App\Http\Interceptor->___callPlugins('catchException', Array, Array) 
#16 /html/lib/internal/Magento/Framework/App/Bootstrap.php(261): Magento\Framework\App\Http\Interceptor->catchException(Object(Magento\Framework\App\Bootstrap), Object(InvalidArgumentException)) 
#17 /html/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #18 {main}

**Comment by ray-moncada** [comment]
This is the log file information

[2018-10-17 16:56:13] Bitpay.DEBUG: [INFO] In Bitpay_Core_Model_Config_PairingCode::save(): attempting to pair with BitPay with pairing code iM3niP2 [] []
[2018-10-17 16:56:13] Bitpay.DEBUG: [INFO] In \Bitpay\Core\Helper\Data::sendPairingRequest(): function called with the pairingCode parameter: iM3niP2 [] []
[2018-10-17 16:56:13] Bitpay.DEBUG: [INFO] In \Bitpay\Core\Helper\Data::registerAutoloader(): autoloader file was found and has been registered. [] []
[2018-10-17 16:56:13] Bitpay.DEBUG: [INFO] In \Bitpay\Core\Helper\Data::generateAndSaveKeys(): attempting to generate new keypair and save to database. [] []
[2018-10-17 16:56:13] Bitpay.DEBUG: [INFO] In \Bitpay\Core\Helper\Data::getKeyManager(): successfully created new BitPay KeyManager object. [] []
[2018-10-17 16:56:13] Bitpay.DEBUG: [INFO] In \Bitpay\Core\Helper\Data::generateAndSaveKeys(): key manager called to persist keypair to database. [] []
[2018-10-17 16:56:13] Bitpay.DEBUG: [INFO] In \Bitpay\Core\Helper\Data::getSinKey(): attempting to get the SIN parameter. [] []
[2018-10-17 16:56:13] Bitpay.DEBUG: [INFO] In \Bitpay\Core\Helper\Data::getPublicKey(): found an existing public key, returning that. [] []
[2018-10-17 16:56:13] Bitpay.DEBUG: [INFO] In \Bitpay\Core\Helper\Data::sendPairingRequest(): attempting to pair with the SIN parameter: "REMOVE FOR SECURITY REASONS" [] []
[2018-10-17 16:56:13] Bitpay.DEBUG: [INFO] In \Bitpay\Core\Helper\Data::sendPairingRequest(): using the label "Magento English". [] []
[2018-10-17 16:56:13] Bitpay.DEBUG: [INFO] In \Bitpay\Core\Helper\Data::getBitpayClient(): successfully created new BitPay Client object. [] []
[2018-10-17 16:56:13] Bitpay.DEBUG: [INFO] In \Bitpay\Core\Helper\Data::getPublicKey(): found an existing public key, returning that. [] []
[2018-10-17 16:56:13] Bitpay.DEBUG: [INFO] In \Bitpay\Core\Helper\Data::getPrivateKey(): found an existing private key, returning that. [] []
[2018-10-17 16:56:13] Bitpay.DEBUG: [INFO] In \Bitpay\Core\Helper\Data::getToken(): successfully created new BitPay Token object. [] []
[2018-10-17 16:56:14] Bitpay.DEBUG: [INFO] In \Bitpay\Core\Helper\Data::sendPairingRequest(): token successfully obtained. [] []
[2018-10-17 16:56:14] Bitpay.DEBUG: [INFO] In \Bitpay\Core\Helper\Data::sendPairingRequest(): token saved to database. [] []
